# Copyright (C) 2015 The Dokdo Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/c1skt/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/c1skt/proprietary/sbin/cbd:root/sbin/cbd

PRODUCT_COPY_FILES += \
    vendor/samsung/c1skt/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/c1skt/proprietary/lib/hw/sensors.smdk4x12.so:system/lib/hw/sensors.smdk4x12.so \
    vendor/samsung/c1skt/proprietary/lib/hw/gps.exynos4.so:system/lib/hw/gps.exynos4.so \
    vendor/samsung/c1skt/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/c1skt/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/c1skt/proprietary/usr/keylayout/sec_touchkey.kl:system/usr/keylayout/sec_touchkey.kl \
    vendor/samsung/c1skt/proprietary/bin/check.sh:system/bin/check.sh \
    vendor/samsung/c1skt/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/c1skt/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/c1skt/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/c1skt/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/c1skt/proprietary/modem/modem_c1ktt.bin:system/modem/modem_c1ktt.bin \
    vendor/samsung/c1skt/proprietary/modem/modem_c1skt.bin:system/modem/modem_c1skt.bin
